Handle numpy ints in resize operations
After the changes in 59028f33b3e93d6c69913117e612c2f1a8129735 we no
longer handle numpy integer types in `resize`:
```
In [1]: with h5py.File('/tmp/foo.h5', 'w') as f:
   ...:     vf = VersionedHDF5File(f)
   ...:     with vf.stage_version('r0') as sv:
   ...:         sv.create_dataset('values', data=np.arange(123), chunks=(10,))
   ...:
[PYFLYBY] from versioned_hdf5 import VersionedHDF5File
[PYFLYBY] import h5py
[PYFLYBY] import numpy as np

In [2]: with h5py.File('/tmp/foo.h5', 'r+') as f:
   ...:     vf = VersionedHDF5File(f)
   ...:     with vf.stage_version('r1') as sv:
   ...:         old_length = sv['values'].size
   ...:         new_length = old_length - 17
   ...:         sv['values'].resize((new_length,))
   ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 6
      4 old_length = sv['values'].size
      5 new_length = old_length - 17
----> 6 sv['values'].resize((new_length,))

File /codemill/bessen/infra/versioned_hdf5/venv/lib64/python3.11/site-packages/versioned_hdf5/wrappers.py:747, in InMemoryDataset.resize(self, size, axis)
    744 size = tuple(size)
    745 # === END CODE FROM h5py.Dataset.resize ===
--> 747 self.staged_changes.resize(size)
    748 self.id.shape = size

File staged_changes.pyx:514, in versioned_hdf5.staged_changes.StagedChangesArray.resize()

File staged_changes.pyx:370, in versioned_hdf5.staged_changes.StagedChangesArray._resize_plan()

File staged_changes.pyx:1324, in versioned_hdf5.staged_changes.ResizePlan.__init__()

File staged_changes.pyx:1402, in versioned_hdf5.staged_changes.ResizePlan._shrink_along_axis()

TypeError: Expected int, got numpy.int64
```

This change fixes that regression.